services:
  mysql:
    image: mysql:8.4.5
    container_name: fdtb-mysql
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d:ro
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_DATABASE=test
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "bash", "-lc", "mysqladmin ping -h 127.0.0.1 -prootpasswd || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 20

  kafka:
    image: confluentinc/cp-kafka:7.9.4
    container_name: fdtb-kafka
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093

      - CLUSTER_ID=Gs7mTXbgRHatmyOilFDsnw

      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:19092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092,CONTROLLER://kafka:9093

      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    healthcheck:
      test: [ "CMD", "bash", "-lc", "kafka-topics --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      timeout: 5s
      retries: 20

  clickhouse:
    image: clickhouse/clickhouse-server:25.3
    container_name: fdtb-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./docker/clickhouse/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - CLICKHOUSE_DB=events
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=passwd
    depends_on:
      kafka:
        condition: service_healthy

  grafana:
    image: grafana/grafana:main
    container_name: fdtb-grafana
    ports:
      - "3300:3000"
    environment:
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - clickhouse

  zipkin:
    image: ghcr.io/openzipkin/zipkin:latest
    container_name: fdtb-zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=rootpasswd
      - MYSQL_DB=zipkin
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    command: --logging.level.zipkin2=DEBUG
    depends_on:
      mysql:
        condition: service_healthy

  zipkin-dependencies:
    image: ghcr.io/openzipkin/zipkin-dependencies:latest
    container_name: fdtb-zipkin-dependencies
    user: root
    entrypoint: /usr/sbin/crond -f
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=rootpasswd
    depends_on:
      mysql:
        condition: service_healthy
